CREATE TABLE IF NOT EXISTS Samples(
    id int AUTO_INCREMENT PRIMARY KEY,
    message VARCHAR(140),
    active_date DATE,
    is_active TINYINT(1) DEFAULT 0,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP
)